[package]
name = "links"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["janm-dev"]
description = "An easy to set up selfhostable link shortener."
license = ""
repository = "https://github.com/janm-dev/links"
rust-version = "1.59"

[features]

[dependencies]
anyhow = "1.0.56"
async-trait = "0.1.52"
hyper = "0.14.18"
lazy_static = "1.4.0"
prost = "0.10.0"
rand = "0.8.5"
regex = "1.5.5"
serde = "1.0.136"
serde_derive = "1.0.136"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["rt-multi-thread"] }
tonic = { version = "0.7.1", features = ["compression", "tls"] }
tracing = "0.1.32"
tracing-subscriber = "0.3.10"
unicode-normalization = "0.1.19"
uriparse = "0.6.4"

[build-dependencies]
tonic-build = { version = "0.7.0", features = ["compression"] }

[profile.release]
incremental = false
debug = 0
lto = true
codegen-units = 1
opt-level = 3
panic = "unwind"
strip = true
