[graph]
all-features = true
targets = [
	"x86_64-unknown-linux-gnu",
	"aarch64-unknown-linux-gnu",
	"x86_64-unknown-linux-musl",
	"aarch64-apple-darwin",
	"x86_64-apple-darwin",
	"x86_64-pc-windows-msvc",
]

[advisories]
version = 2
ignore = []

[licenses]
version = 2
confidence-threshold = 0.9
allow = [
	"Unlicense",        # https://spdx.org/licenses/Unlicense
	"CC0-1.0",          # https://spdx.org/licenses/CC0-1.0
	"ISC",              # https://spdx.org/licenses/ISC
	"MIT",              # https://spdx.org/licenses/MIT
	"BSD-3-Clause",     # https://spdx.org/licenses/BSD-3-Clause
	"Apache-2.0",       # https://spdx.org/licenses/Apache-2.0
	"MPL-2.0",          # https://spdx.org/licenses/MPL-2.0
	"Unicode-DFS-2016", # https://spdx.org/licenses/Unicode-DFS-2016
	"Unicode-3.0",      # https://spdx.org/licenses/Unicode-3.0
]
exceptions = [
	{ name = "links", version = "*", allow = [
		"AGPL-3.0", # https://spdx.org/licenses/AGPL-3.0-or-later
	] },
	{ name = "links-id", version = "*", allow = [
		"AGPL-3.0", # https://spdx.org/licenses/AGPL-3.0-or-later
	] },
	{ name = "links-normalized", version = "*", allow = [
		"AGPL-3.0", # https://spdx.org/licenses/AGPL-3.0-or-later
	] },
	{ name = "links-domainmap", version = "*", allow = [
		"AGPL-3.0", # https://spdx.org/licenses/AGPL-3.0-or-later
	] },
	{ name = "ring", version = "*", allow = [
		"OpenSSL", # https://spdx.org/licenses/OpenSSL
	] },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[[licenses.clarify]]
name = "rustls-webpki"
version = "*"
expression = "ISC"
license-files = [{ path = "LICENSE", hash = 0x001c7e6c }]

[licenses.private]
ignore = false

[bans]
multiple-versions = "allow"
wildcards = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
