# Links redirector server example/default configuration. This file lists all
# options and (mostly) their default values, along with their possible values.
# If any of these options are not specified in the actual configuration file,
# these default values are used.

# The minimum level of logs to retain
# Possible values are "trace", "debug", "verbose", "info", "warn" / "warning", and "error"
log_level = "info"

# Secret API token used to authenticate with the gRPC API
# Can be any string, but should ideally be long and random
token = "random secret api token value"

# Incoming connections will be processed by listeners on the following addresses.
#
# The format for these is `protocol:ip-address:port`, but the address can be
# omitted to listen on all local addresses (IPv4 and IPv6). If the port is not
# specified, the default port for the protocol will be used. The protocol can
# not be omitted.
#
# IP address `0.0.0.0` can be used to listen on all IPv4 (but not IPv6)
# addresses, and `[::]` can be used to listen on all IPv6 (but not IPv4)
# addresses. Note that support for dual stack sockets (IPv4 and IPv6 in one
# listener) is not universally available. On platforms which don't support dual
# stack sockets an empty address will listen on IPv6 only (just like `[::]`). To
# listen on IPv4 and IPv6, two listeners must be used, one listening on
# `0.0.0.0` and the other on `[::]` with the same protocol and port.
#
# Links supports the following protocols:
# - `http` for unencrypted HTTP/1.0, HTTP/1.1, and HTTP/2 (default port 80)
# - `https` for TLS-encrypted HTTP/1.0, HTTP/1.1, and HTTP/2 (default port 443)
# - `grpc` for unencrypted gRPC over HTTP/2 (default port 50051)
# - `grpcs` for TLS-encrypted gRPC over HTTP/2 (default port 530)
#
# TLS-encrypted listeners can be configured even when TLS is disabled, but will
# reject all incoming connections unless TLS is enabled and configured with a
# valid certificate and key.
listeners = [
	"http:0.0.0.0:80",
	"http:[::]:80",
	"https::",
	"grpc:127.0.0.1:",
	"grpc:[::1]:",
	"grpcs::530",
]

# Enable/disable TLS for HTTPS and encrypted gRPC
# Can be true to enable TLS, or false to disable
tls_enable = true

# Path to the TLS key, encoded in PEM format
tls_key = "path/to/key.pem"

# Path to the TLS cert, encoded in PEM format
tls_cert = "path/to/cert.pem"

# Enable/disable HTTP strict transport security
# Possible values are "disable" / "off", "enable" / "on", "include" / "includeSubDomains", and "preload"
# Be VERY careful with "include" / "includeSubDomains" and "preload", as they
# might affect other unrelated HTTP servers on links' host and its subdomains.
# More info on https://hstspreload.org/,
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security,
# and https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security.
hsts = "enable"

# The max-age attribute of the HSTS header in seconds
hsts_max_age = 63072000

# Whether to redirect HTTP requests to HTTPS before the external redirect
# Can be true to enable the forced HTTP to HTTPS redirect, or false to disable
https_redirect = false

# Whether to send the Alt-Svc HTTP header advertising h2 (HTTP/2.0 with TLS)
# support on port 443
# Can be true to enable sending the header, or false to disable
send_alt_svc = false

# Whether to send the Server HTTP header
# Can be true to enable sending the header, or false to disable
send_server = true

# Whether to send the Content-Security-Policy HTTP header
# Can be true to enable sending the header, or false to disable
send_csp = true

# The type of store backend to use
# Possible values are "memory" and "redis"
store = "memory"

# Store-specific backend configuration, more information in the store
# documentation (in src/store/*.rs)
[store_config]
option = "value"
