# Links redirector server example/default configuration. This file lists all
# options and (mostly) their default values, along with their possible values.
# If any of these options are not specified in the actual configuration file,
# these default values are used.

# The minimum level of logs to retain
# Possible values are "trace", "debug", "info", "warn" / "warning", and "error"
log_level: info

# Secret API token used to authenticate with the gRPC API
# Can be any string, but should ideally be long and random
token: random secret api token value

# Enable/disable TLS for HTTPS and encrypted gRPC
# Possible values are "disable" / "off", "enable" / "on", and "force"
tls: disable

# Path to the TLS key, encoded in PEM format
tls_key: path/to/key.pem

# Path to the TLS cert, encoded in PEM format
tls_cert: path/to/cert.pem

# Enable/disable HTTP strict transport security
# Possible values are "disable" / "off", "enable" / "on", "include" / "includeSubDomains", and "preload"
# Be VERY careful with "include" / "includeSubDomains" and "preload", as they
# might affect other unrelated HTTP servers on links' host and its subdomains.
# More info on https://hstspreload.org/,
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security,
# and https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security.
hsts: enable

# The max-age attribute of the HSTS header in seconds
hsts_max_age: 63072000

# Whether to send the Alt-Svc HTTP header advertising h2 (HTTP/2.0 with TLS)
# support on port 443
# Can be true to enable sending the header, or false to disable
send_alt_svc: false

# Whether to send the Server HTTP header
# Can be true to enable sending the header, or false to disable
send_server: true

# Whether to send the Content-Security-Policy HTTP header
# Can be true to enable sending the header, or false to disable
send_csp: true

# The type of store backend to use
# Possible values are "memory" and "redis"
store: memory

# Store-specific backend configuration, more information in the store
# documentation (in src/store/*.rs)
store_config:
  option: value
