[package]
name = "links-normalized"
version = "0.2.0"
edition = "2021"
publish = false
authors = ["janm-dev"]
description = "Easy to use case-insensitive normalized unicode strings and web URLs."
license = "AGPL-3.0-or-later"
repository = "https://github.com/janm-dev/links"
rust-version = "1.62"

[features]
# Support for conversion to/from Redis types using `fred`
fred = ["dep:fred"]

[dependencies]
fred = { version = "5.2.0", optional = true, default-features = false }
serde = "1.0.152"
serde_derive = "1.0.152"
thiserror = "1.0.38"
unicode-normalization = "0.1.22"
uriparse = "0.6.4"
