[package]
name = "links"
version = "0.2.0"
edition = "2021"
publish = false
authors = ["janm-dev"]
description = "An easy to set up selfhostable link shortener."
license = "AGPL-3.0-or-later"
repository = "https://github.com/janm-dev/links"
rust-version = "1.70"
default-run = "server"

[features]
# Run tests involving a Redis server. Needs a running links-compatible Redis
# server on localhost:6379 (TCP) and localhost:6380 (TLS) when running tests.
test-redis = []

[dependencies]
links-id = { path = "../links-id", version = "*", features = [
	"fred",
] }
links-normalized = { path = "../links-normalized", version = "*", features = [
	"fred",
] }
links-domainmap = { path = "../links-domainmap", version = "*", features = [
	"serde",
] }
anyhow = "1.0.75"
async-trait = "0.1.74"
basic-toml = "0.1.7"
clap = { version = "4.3.24", features = ["derive", "env"] }
colored = "2.0.4"
fred = { version = "6.3.2", features = [
	"metrics",
	"enable-rustls",
	"reconnect-on-auth-error",
	"partial-tracing",
] }
hyper = "0.14.27"
notify = "6.1.1"
parking_lot = "0.12.1"
pico-args = { version = "0.5.0", features = [
	"combined-flags",
], default-features = false }
prost = "0.11.9"
rand = "0.8.5"
regex = "1.10.2"
rustls-pemfile = "1.0.3"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
serde_yaml = "0.9.27"
socket2 = "0.5.5"
thiserror = "1.0.50"
time = { version = "0.3.23", features = [
	"macros",
	"parsing",
	"formatting",
] }
tokio = { version = "1.33.0", features = [
	"rt-multi-thread",
] }
tokio-rustls = "0.24.1"
tonic = { version = "0.9.2", default-features = false, features = [
	"gzip",
	"tls",
	"tls-roots",
	"channel",
	"codegen",
	"prost",
] }
tracing = "0.1.40"
tracing-appender = { version = "0.2.2", features = [
	"parking_lot",
] }
tracing-subscriber = "0.3.17"
strum = { version = "0.24.1", features = ["derive"] }
crossbeam-channel = "0.5.8"

[build-dependencies]
base64 = "0.21.5"
lol_html = "1.2.0"
minify-html = "0.11.1"
sha2 = "0.10.8"
tonic-build = "0.9.2"

[dev-dependencies]
regex = "1.10.2"
reqwest = { version = "0.11.22", default-features = false, features = [
	"rustls-tls-native-roots",
	"gzip",
] }
serial_test = "2.0.0"
tokio = { version = "1.33.0", features = ["full"] }
