[package]
name = "links"
version = "0.2.0"
edition = "2021"
publish = false
authors = ["janm-dev"]
description = "An easy to set up selfhostable link shortener."
license = "AGPL-3.0-or-later"
repository = "https://github.com/janm-dev/links"
rust-version = "1.74"
default-run = "server"

[features]
# Run tests involving a Redis server. Needs a running links-compatible Redis
# server on localhost:6379 (TCP) and localhost:6380 (TLS) when running tests.
test-redis = []

[dependencies]
links-id = { path = "../links-id", version = "*", features = [
	"fred",
] }
links-normalized = { path = "../links-normalized", version = "*", features = [
	"fred",
] }
links-domainmap = { path = "../links-domainmap", version = "*", features = [
	"serde",
] }
anyhow = "1.0.81"
async-trait = "0.1.78"
basic-toml = "0.1.9"
clap = { version = "4.5.3", features = ["derive", "env"] }
colored = "2.1.0"
fred = { version = "8.0.5", features = [
	"metrics",
	"enable-rustls",
	"partial-tracing",
] }
hyper = "0.14.28"
notify = "6.1.1"
parking_lot = "0.12.1"
pico-args = { version = "0.5.0", features = [
	"combined-flags",
], default-features = false }
prost = "0.12.3"
rand = "0.8.5"
regex = "1.10.3"
rustls-pemfile = "2.1.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_yaml = "0.9.33"
socket2 = "0.5.6"
thiserror = "1.0.58"
time = { version = "0.3.34", features = [
	"macros",
	"parsing",
	"formatting",
] }
tokio = { version = "1.36.0", features = [
	"rt-multi-thread",
] }
tokio-rustls = { version = "0.25.0", default-features = false, features = [
	"logging",
	"ring",
	"tls12",
] }
tonic = { version = "0.11.0", default-features = false, features = [
	"gzip",
	"tls",
	"tls-roots",
	"channel",
	"codegen",
	"prost",
] }
tracing = "0.1.40"
tracing-appender = { version = "0.2.3", features = [
	"parking_lot",
] }
tracing-subscriber = "0.3.18"
strum = { version = "0.26.2", features = ["derive"] }
crossbeam-channel = "0.5.12"

[build-dependencies]
base64 = "0.22.0"
lol_html = "1.2.1"
minify-html = "0.15.0"
sha2 = "0.10.8"
tonic-build = "0.11.0"

[dev-dependencies]
regex = "1.10.3"
reqwest = { version = "0.11.27", default-features = false, features = [
	"rustls-tls-native-roots",
	"gzip",
] }
serial_test = "3.0.0"
tokio = { version = "1.36.0", features = ["full"] }
