name: Audit

on:
  push:
  pull_request:
  schedule:
    - cron: "30 12 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    name: Regular Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        id: install-toolchain
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
      - uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/
          key: cargo-audit-and-outdated-${{ steps.install-toolchain.outputs.rustc_hash }}
      - run: cargo install cargo-audit cargo-outdated
      - uses: EmbarkStudios/cargo-deny-action@v1
        if: success() || failure()
      - uses: actions/dependency-review-action@v2
        if: (success() || failure()) && (github.event_name == 'pull_request' || github.event_name == 'pull_request_target')
        with:
          fail-on-severity: low
      - run: cargo outdated --exit-code 1
        if: success() || failure()
      - run: cargo audit -D warnings
        if: success() || failure()
