name: Audit

on:
  schedule:
    - cron: "0 12 */7 * *"
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    name: Weekly Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
