name: CI

on: [push, pull_request]

env:
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo check

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly clippy -- -D warnings

  test:
    name: Test and report coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: sudo apt-get install -y ca-certificates && sudo cp ${{ github.workspace }}/links/tests/cert.pem /usr/local/share/ca-certificates/test-cert.crt && sudo update-ca-certificates && sudo /sbin/iptables -F && printf 'net.ipv4.ip_unprivileged_port_start = 50\nnet.ipv6.ip_unprivileged_port_start = 50\n' | sudo tee /etc/sysctl.d/50-unprivileged-ports.conf && sudo sysctl --system
      - run: docker run -d -p 6379:6379 -p 6380:6380 -v ${{ github.workspace }}/links/tests/cert.pem:/cert.pem:ro -v ${{ github.workspace }}/links/tests/key.pem:/key.pem:ro redis:7.0-alpine --tls-port 6380 --tls-auth-clients no --tls-cert-file /cert.pem --tls-key-file /key.pem
      - uses: Swatinem/rust-cache@v2
      - run: cargo llvm-cov clean && cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
