name: Documentation

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: pages-docs
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: arduino/setup-protoc@v3
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/configure-pages@v2
        id: pages
      - run: |
          cargo doc --no-deps --document-private-items --all-features
          cat misc/docs.html > target/doc/index.html
      - uses: actions/upload-pages-artifact@v1
        with:
          path: target/doc
      - uses: actions/deploy-pages@v1
        id: deployment
