name: Tests with external services

on: [push, pull_request]

jobs:
  test-redis-latest:
    name: Test with latest Redis
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: "--features redis-tests"

  test-redis-70:
    name: Test with Redis 7.0
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7.0-alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: "--features redis-tests"

  test-redis-62:
    name: Test with Redis 6.2
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6.2-alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: "--features redis-tests"

  # test-redis-60:
  #   name: Test with Redis 6.0
  #   runs-on: ubuntu-latest
  #   services:
  #     redis:
  #       image: redis:6.0-alpine
  #       ports:
  #         - 6379:6379
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         profile: minimal
  #         toolchain: stable
  #         override: true
  #     - uses: actions-rs/cargo@v1
  #       with:
  #         command: test
  #         args: "--features redis-tests"

  # test-redis-50:
  #   name: Test with Redis 5.0
  #   runs-on: ubuntu-latest
  #   services:
  #     redis:
  #       image: redis:5.0-alpine
  #       ports:
  #         - 6379:6379
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         profile: minimal
  #         toolchain: stable
  #         override: true
  #     - uses: actions-rs/cargo@v1
  #       with:
  #         command: test
  #         args: "--features redis-tests"
