name: Compatibility tests

on: [push, pull_request]

env:
  RUST_BACKTRACE: 1

jobs:
  test-docker:
    name: Test Docker container build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . -t links:test

  test-rust:
    strategy:
      fail-fast: false
      matrix:
        version: ["1.62", stable, beta]
    name: Test with Rust ${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.version }}
          override: true
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
      - run: sudo apt-get install -y ca-certificates && sudo cp ${{ github.workspace }}/tests/cert.pem /usr/local/share/ca-certificates/test-cert.crt && sudo update-ca-certificates && sudo /sbin/iptables -F && printf 'net.ipv4.ip_unprivileged_port_start = 50\nnet.ipv6.ip_unprivileged_port_start = 50\n' | sudo tee /etc/sysctl.d/50-unprivileged-ports.conf && sudo sysctl --system
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: test

  test-redis:
    strategy:
      fail-fast: false
      matrix:
        version: [6.2-alpine, 7.0-alpine]
    name: Test with Redis ${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
      - run: sudo apt-get install -y ca-certificates && sudo cp ${{ github.workspace }}/tests/cert.pem /usr/local/share/ca-certificates/test-cert.crt && sudo update-ca-certificates && sudo /sbin/iptables -F && printf 'net.ipv4.ip_unprivileged_port_start = 50\nnet.ipv6.ip_unprivileged_port_start = 50\n' | sudo tee /etc/sysctl.d/50-unprivileged-ports.conf && sudo sysctl --system
      - run: docker run -d -p 6379:6379 -p 6380:6380 -v ${{ github.workspace }}/tests/cert.pem:/cert.pem:ro -v ${{ github.workspace }}/tests/key.pem:/key.pem:ro redis:${{ matrix.version }} --tls-port 6380 --tls-auth-clients no --tls-cert-file /cert.pem --tls-key-file /key.pem
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: "--features redis-tests"
