name: Compatibility tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

env:
  RUST_BACKTRACE: 1

jobs:
  test-docker:
    name: Test Docker container
    runs-on: ubuntu-latest
    env:
      LINKS_TEST_EXTERNAL: docker
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: arduino/setup-protoc@v3
        with:
          version: "23.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build . -t links:test
      - run: sudo apt-get install -y ca-certificates && sudo cp ${{ github.workspace }}/links/tests/cert.pem /usr/local/share/ca-certificates/test-cert.crt && sudo update-ca-certificates && sudo /sbin/iptables -F && printf 'net.ipv4.ip_unprivileged_port_start = 50\nnet.ipv6.ip_unprivileged_port_start = 50\n' | sudo tee /etc/sysctl.d/50-unprivileged-ports.conf && sudo sysctl --system
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --test '*'

  test-rust:
    strategy:
      fail-fast: false
      matrix:
        version: ["1.77", stable, beta]
    name: Test with Rust ${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.version }}
      - uses: arduino/setup-protoc@v3
        with:
          version: "23.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: sudo apt-get install -y ca-certificates && sudo cp ${{ github.workspace }}/links/tests/cert.pem /usr/local/share/ca-certificates/test-cert.crt && sudo update-ca-certificates && sudo /sbin/iptables -F && printf 'net.ipv4.ip_unprivileged_port_start = 50\nnet.ipv6.ip_unprivileged_port_start = 50\n' | sudo tee /etc/sysctl.d/50-unprivileged-ports.conf && sudo sysctl --system
      - uses: Swatinem/rust-cache@v2
      - run: cargo test

  test-redis:
    strategy:
      fail-fast: false
      matrix:
        version: [6.2-alpine, 7.0-alpine]
    name: Test with Redis ${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: arduino/setup-protoc@v3
        with:
          version: "23.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: sudo apt-get install -y ca-certificates && sudo cp ${{ github.workspace }}/links/tests/cert.pem /usr/local/share/ca-certificates/test-cert.crt && sudo update-ca-certificates && sudo /sbin/iptables -F && printf 'net.ipv4.ip_unprivileged_port_start = 50\nnet.ipv6.ip_unprivileged_port_start = 50\n' | sudo tee /etc/sysctl.d/50-unprivileged-ports.conf && sudo sysctl --system
      - run: docker run -d -p 6379:6379 -p 6380:6380 -v ${{ github.workspace }}/links/tests/cert.pem:/cert.pem:ro -v ${{ github.workspace }}/links/tests/key.pem:/key.pem:ro redis:${{ matrix.version }} --tls-port 6380 --tls-auth-clients no --tls-cert-file /cert.pem --tls-key-file /key.pem
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --features test-redis

  test-domainmap:
    strategy:
      fail-fast: false
      matrix:
        version: ["1.65", "1.77", stable, beta]
        features:
          ["", "--features=std", "--features=serde", "--features=std,serde"]
    name: Test links-domainmap with features "${{ matrix.features }}" on Rust ${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.version }}
      - uses: Swatinem/rust-cache@v2
      - run: cd links-domainmap && cargo test --no-default-features ${{ matrix.features }}
